POKEMON_LIST = [
    # Gen 1 — Starters
    {"name": "Bulbasaur",   "generation": 1, "type_1": "Grass",  "type_2": "Poison"},
    {"name": "Ivysaur",     "generation": 1, "type_1": "Grass",  "type_2": "Poison"},
    {"name": "Venusaur",    "generation": 1, "type_1": "Grass",  "type_2": "Poison"},
    {"name": "Charmander",  "generation": 1, "type_1": "Fire",   "type_2": None},
    {"name": "Charmeleon",  "generation": 1, "type_1": "Fire",   "type_2": None},
    {"name": "Charizard",   "generation": 1, "type_1": "Fire",   "type_2": "Flying"},
    {"name": "Squirtle",    "generation": 1, "type_1": "Water",  "type_2": None},
    {"name": "Wartortle",   "generation": 1, "type_1": "Water",  "type_2": None},
    {"name": "Blastoise",   "generation": 1, "type_1": "Water",  "type_2": None},
    # Gen 2
    {"name": "Chikorita",   "generation": 2, "type_1": "Grass",  "type_2": None},
    {"name": "Bayleef",     "generation": 2, "type_1": "Grass",  "type_2": None},
    {"name": "Meganium",    "generation": 2, "type_1": "Grass",  "type_2": None},
    {"name": "Cyndaquil",   "generation": 2, "type_1": "Fire",   "type_2": None},
    {"name": "Quilava",     "generation": 2, "type_1": "Fire",   "type_2": None},
    {"name": "Typhlosion",  "generation": 2, "type_1": "Fire",   "type_2": None},
    {"name": "Totodile",    "generation": 2, "type_1": "Water",  "type_2": None},
    {"name": "Croconaw",    "generation": 2, "type_1": "Water",  "type_2": None},
    {"name": "Feraligatr",  "generation": 2, "type_1": "Water",  "type_2": None},
    # Gen 3
    {"name": "Treecko",     "generation": 3, "type_1": "Grass",  "type_2": None},
    {"name": "Grovyle",     "generation": 3, "type_1": "Grass",  "type_2": None},
    {"name": "Sceptile",    "generation": 3, "type_1": "Grass",  "type_2": None},
    {"name": "Torchic",     "generation": 3, "type_1": "Fire",   "type_2": None},
    {"name": "Combusken",   "generation": 3, "type_1": "Fire",   "type_2": "Fighting"},
    {"name": "Blaziken",    "generation": 3, "type_1": "Fire",   "type_2": "Fighting"},
    {"name": "Mudkip",      "generation": 3, "type_1": "Water",  "type_2": None},
    {"name": "Marshtomp",   "generation": 3, "type_1": "Water",  "type_2": "Ground"},
    {"name": "Swampert",    "generation": 3, "type_1": "Water",  "type_2": "Ground"},
    # Gen 4
    {"name": "Turtwig",     "generation": 4, "type_1": "Grass",  "type_2": None},
    {"name": "Grotle",      "generation": 4, "type_1": "Grass",  "type_2": None},
    {"name": "Torterra",    "generation": 4, "type_1": "Grass",  "type_2": "Ground"},
    {"name": "Chimchar",    "generation": 4, "type_1": "Fire",   "type_2": None},
    {"name": "Monferno",    "generation": 4, "type_1": "Fire",   "type_2": "Fighting"},
    {"name": "Infernape",   "generation": 4, "type_1": "Fire",   "type_2": "Fighting"},
    {"name": "Piplup",      "generation": 4, "type_1": "Water",  "type_2": None},
    {"name": "Prinplup",    "generation": 4, "type_1": "Water",  "type_2": None},
    {"name": "Empoleon",    "generation": 4, "type_1": "Water",  "type_2": "Steel"},
    # Gen 5
    {"name": "Snivy",       "generation": 5, "type_1": "Grass",  "type_2": None},
    {"name": "Servine",     "generation": 5, "type_1": "Grass",  "type_2": None},
    {"name": "Serperior",   "generation": 5, "type_1": "Grass",  "type_2": None},
    {"name": "Tepig",       "generation": 5, "type_1": "Fire",   "type_2": None},
    {"name": "Pignite",     "generation": 5, "type_1": "Fire",   "type_2": "Fighting"},
    {"name": "Emboar",      "generation": 5, "type_1": "Fire",   "type_2": "Fighting"},
    {"name": "Oshawott",    "generation": 5, "type_1": "Water",  "type_2": None},
    {"name": "Dewott",      "generation": 5, "type_1": "Water",  "type_2": None},
    {"name": "Samurott",    "generation": 5, "type_1": "Water",  "type_2": None},
    # Gen 6
    {"name": "Chespin",     "generation": 6, "type_1": "Grass",  "type_2": None},
    {"name": "Quilladin",   "generation": 6, "type_1": "Grass",  "type_2": None},
    {"name": "Chesnaught",  "generation": 6, "type_1": "Grass",  "type_2": "Fighting"},
    {"name": "Fennekin",    "generation": 6, "type_1": "Fire",   "type_2": None},
    {"name": "Braixen",     "generation": 6, "type_1": "Fire",   "type_2": None},
    {"name": "Delphox",     "generation": 6, "type_1": "Fire",   "type_2": "Psychic"},
    {"name": "Froakie",     "generation": 6, "type_1": "Water",  "type_2": None},
    {"name": "Frogadier",   "generation": 6, "type_1": "Water",  "type_2": None},
    {"name": "Greninja",    "generation": 6, "type_1": "Water",  "type_2": "Dark"},
    # Gen 7
    {"name": "Rowlet",      "generation": 7, "type_1": "Grass",  "type_2": "Flying"},
    {"name": "Dartrix",     "generation": 7, "type_1": "Grass",  "type_2": "Flying"},
    {"name": "Decidueye",   "generation": 7, "type_1": "Grass",  "type_2": "Ghost"},
    {"name": "Litten",      "generation": 7, "type_1": "Fire",   "type_2": None},
    {"name": "Torracat",    "generation": 7, "type_1": "Fire",   "type_2": None},
    {"name": "Incineroar",  "generation": 7, "type_1": "Fire",   "type_2": "Dark"},
    {"name": "Popplio",     "generation": 7, "type_1": "Water",  "type_2": None},
    {"name": "Brionne",     "generation": 7, "type_1": "Water",  "type_2": None},
    {"name": "Primarina",   "generation": 7, "type_1": "Water",  "type_2": "Fairy"},
    # Gen 8
    {"name": "Grookey",     "generation": 8, "type_1": "Grass",  "type_2": None},
    {"name": "Thwackey",    "generation": 8, "type_1": "Grass",  "type_2": None},
    {"name": "Rillaboom",   "generation": 8, "type_1": "Grass",  "type_2": None},
    {"name": "Scorbunny",   "generation": 8, "type_1": "Fire",   "type_2": None},
    {"name": "Raboot",      "generation": 8, "type_1": "Fire",   "type_2": None},
    {"name": "Cinderace",   "generation": 8, "type_1": "Fire",   "type_2": None},
    {"name": "Sobble",      "generation": 8, "type_1": "Water",  "type_2": None},
    {"name": "Drizzile",    "generation": 8, "type_1": "Water",  "type_2": None},
    {"name": "Inteleon",    "generation": 8, "type_1": "Water",  "type_2": None},
    # Gen 9
    {"name": "Sprigatito",  "generation": 9, "type_1": "Grass",  "type_2": None},
    {"name": "Floragato",   "generation": 9, "type_1": "Grass",  "type_2": None},
    {"name": "Meowscarada", "generation": 9, "type_1": "Grass",  "type_2": "Dark"},
    {"name": "Fuecoco",     "generation": 9, "type_1": "Fire",   "type_2": None},
    {"name": "Crocalor",    "generation": 9, "type_1": "Fire",   "type_2": None},
    {"name": "Skeledirge",  "generation": 9, "type_1": "Fire",   "type_2": "Ghost"},
    {"name": "Quaxly",      "generation": 9, "type_1": "Water",  "type_2": None},
    {"name": "Quaxwell",    "generation": 9, "type_1": "Water",  "type_2": None},
    {"name": "Quaquaval",   "generation": 9, "type_1": "Water",  "type_2": "Fighting"},
    # Special group (generation = 0)
    {"name": "Pikachu",     "generation": 0, "type_1": "Electric", "type_2": None},
    {"name": "Raichu",      "generation": 0, "type_1": "Electric", "type_2": None},
    {"name": "Eevee",       "generation": 0, "type_1": "Normal",   "type_2": None},
    {"name": "Vaporeon",    "generation": 0, "type_1": "Water",    "type_2": None},
    {"name": "Jolteon",     "generation": 0, "type_1": "Electric", "type_2": None},
    {"name": "Flareon",     "generation": 0, "type_1": "Fire",     "type_2": None},
    {"name": "Espeon",      "generation": 0, "type_1": "Psychic",  "type_2": None},
    {"name": "Umbreon",     "generation": 0, "type_1": "Dark",     "type_2": None},
    {"name": "Leafeon",     "generation": 0, "type_1": "Grass",    "type_2": None},
    {"name": "Glaceon",     "generation": 0, "type_1": "Ice",      "type_2": None},
    {"name": "Sylveon",     "generation": 0, "type_1": "Fairy",    "type_2": None},
]
